import Box from '@/components/box/box';
import AdminNavbar from '@/components/layouts/admin/admin-navbar';
import AdminSidebar from '@/components/layouts/admin/admin-sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';
import { allRoutes } from '@/constants/routes.constant';
import { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { PropsWithChildren } from 'react';
import { checkAdminRole } from './actions';

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by Kais Al Husrom',
};

const AdminDashboardLayout = async ({ children }: PropsWithChildren) => {
  // Check if user is authenticated and has admin privileges before rendering the layout
  const isAdmin = await checkAdminRole();

  if (!isAdmin) {
    redirect(allRoutes.home.path);
  }

  return (
    <SidebarProvider>
      <Box className="w-full items-start gap-0 bg-gray-bg ">
        <AdminSidebar />
        <Box className="w-full flex-col items-start">
          <AdminNavbar />
          {children}
        </Box>
      </Box>
    </SidebarProvider>
  );
};

export default AdminDashboardLayout;
