export const getProductsData = (t) => [
        {   id : 1 , 
            title: t('latestOffers.products.product1.title'), 
            marka: t('latestOffers.products.product1.marka'), 
            price: t('latestOffers.products.product1.price'), 
            imageSrc: '/assets/images/car-card.png',
            carType :t('latestOffers.products.product1.carType'), 
            model : t('latestOffers.products.product1.model'), 
            controlType :t('latestOffers.products.product1.controlType'), 
            distance : t('latestOffers.products.product1.distance'), 
            passengers : t('latestOffers.products.product1.passengers'), 
            adsNumber:t('latestOffers.products.product1.adsNumber'), 
            dateOfAds : t('latestOffers.products.product1.dateOfAds'),
            gaz :  t('latestOffers.products.product1.gaz'),
        },
        {   id : 2 ,
            title: t('latestOffers.products.product2.title'),
            marka: t('latestOffers.products.product2.marka'), 
            price: t('latestOffers.products.product2.price'), 
            imageSrc: '/assets/images/car-card.png' ,
            carType :t('latestOffers.products.product2.carType'), 
            model : t('latestOffers.products.product2.model'), 
            controlType :t('latestOffers.products.product2.controlType'), 
            distance : t('latestOffers.products.product2.distance'), 
            passengers : t('latestOffers.products.product2.passengers'), 
            adsNumber:t('latestOffers.products.product2.adsNumber'), 
            dateOfAds : t('latestOffers.products.product2.dateOfAds'),
            gaz :  t('latestOffers.products.product2.gaz'),

        },
        {   id : 3 ,title: t('latestOffers.products.product3.title'), 
            marka: t('latestOffers.products.product3.marka'), 
            price: t('latestOffers.products.product3.price'), 
            imageSrc: '/assets/images/car-card.png' ,
            carType :t('latestOffers.products.product3.carType'), 
            model : t('latestOffers.products.product3.model'), 
            controlType :t('latestOffers.products.product3.controlType'), 
            distance : t('latestOffers.products.product3.distance'), 
            passengers : t('latestOffers.products.product3.passengers'), 
            adsNumber:t('latestOffers.products.product3.adsNumber'), 
            dateOfAds : t('latestOffers.products.product3.dateOfAds'),
            gaz :  t('latestOffers.products.product3.gaz'),

        },
        {   id : 4 ,title: t('latestOffers.products.product4.title'), 
            marka: t('latestOffers.products.product4.marka'), 
            price: t('latestOffers.products.product4.price'), 
            imageSrc: '/assets/images/car-card.png',
            carType :t('latestOffers.products.product4.carType'), 
            model : t('latestOffers.products.product4.model'), 
            controlType :t('latestOffers.products.product4.controlType'), 
            distance : t('latestOffers.products.product4.distance'), 
            passengers : t('latestOffers.products.product4.passengers'), 
            adsNumber:t('latestOffers.products.product4.adsNumber'), 
            dateOfAds : t('latestOffers.products.product4.dateOfAds'),
            gaz :  t('latestOffers.products.product4.gaz'),

        },
        {   id : 5 ,title: t('latestOffers.products.product5.title'), 
            marka: t('latestOffers.products.product5.marka'), 
            price: t('latestOffers.products.product5.price'), 
            imageSrc: '/assets/images/car-card.png',
            carType :t('latestOffers.products.product5.carType'), 
            model : t('latestOffers.products.product5.model'), 
            controlType :t('latestOffers.products.product5.controlType'), 
            distance : t('latestOffers.products.product5.distance'), 
            passengers : t('latestOffers.products.product5.passengers'), 
            adsNumber:t('latestOffers.products.product5.adsNumber'), 
            dateOfAds : t('latestOffers.products.product5.dateOfAds'),
            gaz :  t('latestOffers.products.product5.gaz'),
  
        },
        {   id : 6 ,title: t('latestOffers.products.product6.title'), 
            marka: t('latestOffers.products.product6.marka'), 
            price: t('latestOffers.products.product6.price'), 
            imageSrc: '/assets/images/car-card.png',
            carType :t('latestOffers.products.product6.carType'), 
            model : t('latestOffers.products.product6.model'), 
            controlType :t('latestOffers.products.product6.controlType'), 
            distance : t('latestOffers.products.product6.distance'), 
            passengers : t('latestOffers.products.product6.passengers'), 
            adsNumber:t('latestOffers.products.product6.adsNumber'), 
            dateOfAds : t('latestOffers.products.product6.dateOfAds'),
            gaz :  t('latestOffers.products.product6.gaz'),
  
        },
        {   id : 7 ,title: t('latestOffers.products.product7.title'), 
            marka: t('latestOffers.products.product7.marka'), 
            price: t('latestOffers.products.product7.price'), 
            imageSrc: '/assets/images/car-card.png',
            carType :t('latestOffers.products.product7.carType'), 
            model : t('latestOffers.products.product7.model'), 
            controlType :t('latestOffers.products.product7.controlType'), 
            distance : t('latestOffers.products.product7.distance'), 
            passengers : t('latestOffers.products.product7.passengers'), 
            adsNumber:t('latestOffers.products.product7.adsNumber'), 
            dateOfAds : t('latestOffers.products.product7.dateOfAds'),
            gaz :  t('latestOffers.products.product7.gaz'),
  
        },
        {   id : 8, title: t('latestOffers.products.product8.title'), 
            marka: t('latestOffers.products.product8.marka'), 
            price: t('latestOffers.products.product8.price'), 
            imageSrc: '/assets/images/car-card.png',
            carType :t('latestOffers.products.product8.carType'), 
            model : t('latestOffers.products.product8.model'), 
            controlType :t('latestOffers.products.product8.controlType'), 
            distance : t('latestOffers.products.product8.distance'), 
            passengers : t('latestOffers.products.product8.passengers'), 
            adsNumber:t('latestOffers.products.product8.adsNumber'), 
            dateOfAds : t('latestOffers.products.product8.dateOfAds'),
            gaz :  t('latestOffers.products.product8.gaz'),
  
        },
        {   id : 9 , title: t('latestOffers.products.product9.title'), 
            marka: t('latestOffers.products.product9.marka'), 
            price: t('latestOffers.products.product9.price'), 
            imageSrc: '/assets/images/car-card.png',
            carType :t('latestOffers.products.product9.carType'), 
            model : t('latestOffers.products.product9.model'), 
            controlType :t('latestOffers.products.product9.controlType'), 
            distance : t('latestOffers.products.product9.distance'), 
            passengers : t('latestOffers.products.product9.passengers'), 
            adsNumber:t('latestOffers.products.product9.adsNumber'), 
            dateOfAds : t('latestOffers.products.product9.dateOfAds'),
            gaz :  t('latestOffers.products.product9.gaz'),
  
        },
];

// export const getProductsRentData = (t )=>  [
//     { 
//         id : 1,
//         title: t('rentProduct.products.product1.title'), 
//         marka: t('rentProduct.products.product1.marka'),  
//         price: t('rentProduct.products.product1.price'),     
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//             gaz: t('rentProduct.products.product1.details.basic.gaz'),
//             type: t('rentProduct.products.product1.details.basic.type'),
//             }, 
//     },
//     { 
//         id : 2,
//         title: t('rentProduct.products.product2.title'), 
//         marka: t('rentProduct.products.product2.marka'), 
//         price: t('rentProduct.products.product2.price'),   
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//             gaz: t('rentProduct.products.product1.details.basic.gaz'),
//             type: t('rentProduct.products.product1.details.basic.type'),
//             },
//     },
//     { 
//         id : 3,
//         title: t('rentProduct.products.product3.title'), 
//         marka: t('rentProduct.products.product3.marka'), 
//         price: t('rentProduct.products.product3.price'),
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//         gaz: t('rentProduct.products.product1.details.basic.gaz'),
//         type: t('rentProduct.products.product1.details.basic.type'),
//         }, 
//     },
//     {   
//         id : 4,
//         title: t('rentProduct.products.product4.title'), 
//         marka: t('rentProduct.products.product4.marka'), 
//         price: t('rentProduct.products.product4.price'), 
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//         gaz: t('rentProduct.products.product1.details.basic.gaz'),
//         type: t('rentProduct.products.product1.details.basic.type'),
//         }, 
//     },
//     { 
//         id : 5,
//         title: t('rentProduct.products.product5.title'), 
//         marka: t('rentProduct.products.product5.marka'), 
//         price: t('rentProduct.products.product5.price'),   
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//         gaz: t('rentProduct.products.product1.details.basic.gaz'),
//         type: t('rentProduct.products.product1.details.basic.type'),
//         }, 
//     },
//     { 
//         id : 6,
//         title: t('rentProduct.products.product6.title'), 
//         marka: t('rentProduct.products.product6.marka'), 
//         price: t('rentProduct.products.product6.price'),  
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//         gaz: t('rentProduct.products.product1.details.basic.gaz'),
//         type: t('rentProduct.products.product1.details.basic.type'),
//         }, 
//     },
//     { 
//         id : 7,
//         title: t('rentProduct.products.product7.title'),
//         marka: t('rentProduct.products.product7.marka'), 
//         price: t('rentProduct.products.product7.price'), 
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//         gaz: t('rentProduct.products.product1.details.basic.gaz'),
//         type: t('rentProduct.products.product1.details.basic.type'),
//         }, 
//     },
//     { 
//         id : 8,
//         title: t('rentProduct.products.product8.title'), 
//         marka: t('rentProduct.products.product8.marka'), 
//         price: t('rentProduct.products.product8.price'),
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//         gaz: t('rentProduct.products.product1.details.basic.gaz'),
//         type: t('rentProduct.products.product1.details.basic.type'),
//         }, 
//     },
//     { 
//         id : 8,
//         title: t('rentProduct.products.product9.title'), 
//         marka: t('rentProduct.products.product9.marka'), 
//         price: t('rentProduct.products.product9.price'),  
//         imageSrc: '/assets/images/car-card.png' ,
//         details: {
//         gaz: t('rentProduct.products.product1.details.basic.gaz'),
//         type: t('rentProduct.products.product1.details.basic.type'),
//         }, 
//     },

// ];