import type { Metadata } from 'next';
// import localFont from "next/font/local";
import GlobalProvider from '@/providers/global.provider';
import '../globals.css';
import { initConfigs } from '@/config';

export const metadata: Metadata = {
  title: 'Ecommerce Template',
  description: 'Generated by Kais Al Husrom',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  initConfigs();
  // const { direction } = useLangContext();
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
